services:
  - mongodb
before_script:
  - mongo moletest --eval 'db.createUser({user:"molepaw",pwd:"molepaw",roles:["readWrite"]});'
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install tox-travis
script: tox
