git:
    submodules: false
services:
  - mongodb
  - xvfb
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install: 
  - pip install tox-travis
  - pip install coveralls
script: 
  - tox
  - 'nosetests etl/tests/e2e'
after_success:
  - coveralls
addons:
  - chrome: stable
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/bin/
  - export CHROME_BIN=google-chrome-stable
  - sleep 3 # give xvfb some time to start
  - "gearbox serve -c test_e2e.ini"  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc