- hosts: testservers
  user: aw{{testuser}}
  tasks:
    - name: Get code from repository
      git: repo={{ repository }} dest=/var/www/{{testuser}}/app/{{app_package}}

    - name: Give Ownership of Public Directory to www-data
      command: chown -R aw{{testuser}}:awdemo.axantweb.com /var/www/{{testuser}}/app/{{public_rel_path}}

    - name: Install Python Dependencies
      pip: virtualenv=/var/www/{{testuser}}/penv name='file:///var/www/{{testuser}}/app/{{app_package}}' extra_args={{extra_args}} virtualenv_site_packages=no

    - name: Install tg.devtools if Database Init is required
      pip: virtualenv=/var/www/{{testuser}}/penv name='tg.devtools'

    - name: Configure WSGI
      template: src=wsgi_application.py.j2 dest=/var/www/{{testuser}}/app/wsgi_application.py

    - name: Configure staging.ini
      template: src=staging.ini.j2 dest=/var/www/{{testuser}}/app/{{app_package}}/staging.ini

- hosts: testservers
  user: root
  tasks:
    - name: restart apache2
      service: name=apache2 state=restarted
