"""allow_disable_step

Revision ID: 331ace739944
Revises: None
Create Date: 2015-12-10 15:04:45.905330

"""

# revision identifiers, used by Alembic.
revision = '331ace739944'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_steps', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_steps', 'enabled')
    ### end Alembic commands ###
