"""category

Revision ID: 5b33195692ea
Revises: e767a5addfc9
Create Date: 2019-02-04 19:13:48.507045

"""

# revision identifiers, used by Alembic.
revision = '5b33195692ea'
down_revision = 'e767a5addfc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('category_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'extractions', 'tgappcategories_categories', ['category_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'extractions', type_='foreignkey')
    op.drop_column('extractions', 'category_id')
    # ### end Alembic commands ###
