"""New table for Extraction Filters

Revision ID: e767a5addfc9
Revises: 76d9d7574d09
Create Date: 2018-06-13 14:58:37.088142

"""

# revision identifiers, used by Alembic.
revision = 'e767a5addfc9'
down_revision = '76d9d7574d09'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_filters',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=99), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), default=False, nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_extraction_filters_extraction_id'), 'extraction_filters', ['extraction_id'], unique=False)
    op.add_column('extraction_steps', sa.Column('extraction_filter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_extraction_steps_extraction_filter_id'), 'extraction_steps', ['extraction_filter_id'], unique=False)
    op.create_foreign_key('extraction_steps_ibfk_2', 'extraction_steps', 'extraction_filters', ['extraction_filter_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('extraction_steps_ibfk_2', 'extraction_steps', type_='foreignkey')
    op.drop_index(op.f('ix_extraction_steps_extraction_filter_id'), table_name='extraction_steps')
    op.drop_column('extraction_steps', 'extraction_filter_id')
    op.drop_table('extraction_filters')
    # ### end Alembic commands ###
