---
# handlers file for Configure-Circus


- name: start circus
  command: /usr/local/bin/circusd /etc/circus/circusd.ini --daemon --log-level debug --log-output /var/log/circus/circusd.log

- name: restart circus
  command: /usr/local/bin/circusctl restart